### ISSUE TITLE
Redesign dentallinkapp.com main banner

### ISSUE THREAD

**Issue by paragasu** [phisoft/dentallink-web#23]

**Comment by paragasu** [comment]
Provide suggestions on the header design.

![Image](https://user-images.githubusercontent.com/27353/188808412-8634046a-0d13-441a-af9a-a2598586bfb2.png)

**Comment by lalgal** [comment]
[Dental Link Website Banner.zip](https://github.com/phisoft/dentallink-web/files/9523287/Dental.Link.Website.Banner.zip)

**Comment by lalgal** [comment]
[Dental Link Website Banner.zip](https://github.com/phisoft/dentallink-web/files/9553799/Dental.Link.Website.Banner.zip)
