### ISSUE TITLE
Prepare demo data

### ISSUE THREAD

**Issue by paragasu** [phisoft/dentallink-web#3]
Key in dummy data to demo.dentallinkapp.com

**Comment by jeannyjohanis** [comment]
- Added branches (5 branches)
![image](https://user-images.githubusercontent.com/93868091/156985733-3d74d639-2fe8-4c08-989e-0760a6fcdf68.png)

- Added dentist to each branch (5 dentists)
![image](https://user-images.githubusercontent.com/93868091/156986414-0a0af7c6-9be9-4381-ad7f-fffc1db70931.png)

- Added inventory items (10 items)
![image](https://user-images.githubusercontent.com/93868091/156986508-81680aee-39c7-4ebf-8b6d-ba810134da1e.png)

- Added additional patients
![image](https://user-images.githubusercontent.com/93868091/156986654-d8c21d8c-92ad-4b72-a7ac-8df05baa0d33.png)

- Added appointments to all branches
![image](https://user-images.githubusercontent.com/93868091/156986781-adb19351-56c1-47ed-96f3-5c18ee919af0.png)

- Added reminders
![image](https://user-images.githubusercontent.com/93868091/156987020-32583660-8803-4edf-9b36-c31e18464245.png)

- Added clinical notes and treatment for patients scheduled 7th March 2022
![image](https://user-images.githubusercontent.com/93868091/156987253-7514c591-abaf-4d86-a166-2afeb11659cb.png)
