### ISSUE TITLE
change system image

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/dentallink-web#31]
![image](https://github.com/phisoft/dentallink-web/assets/30463117/367f0615-2f55-46ad-8fa8-8661e1b13458)

**Comment by abigailtaruc** [comment]
https://github.com/phisoft/dentallink-web.git

**Comment by abigailtaruc** [comment]
![image](https://github.com/phisoft/dentallink-web/assets/110286983/0cc73f0c-7411-4f8c-ba4b-1ebb05ba6cca)

**Comment by rosclaritha** [comment]
commit & include the image in the pr @abigailtaruc
