### ISSUE TITLE
fill in mockup data

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/dentallink-web#32]
http://demo.dentallinkapp.com/
login: admin / admin

**Comment by abigailtaruc** [comment]
![image](https://github.com/phisoft/dentallink-web/assets/110286983/3f0f174a-8bda-41ba-a6d8-13a055c685b9)
![image](https://github.com/phisoft/dentallink-web/assets/110286983/93e4faa5-bf51-4b51-bd2d-3ad2dfa21bc1)
![image](https://github.com/phisoft/dentallink-web/assets/110286983/5f747ff8-6f37-4a56-83f4-482e24ad9b90)
